import Head from "next/head";
import Header from "../components/header";
import HomePage from "./HomePage";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NOON Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        />
      </Head>

      <HomePage />
    </div>
  );
}
